using System.Linq;
using DevExpress.XtraEditors;

namespace OOP
{
    public partial class HoatDongCuocThiOnGoing : XtraUserControl
    {
        private HoatDongUEHEntities db;
        public HoatDongCuocThiOnGoing()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            pLinqServerModeSource1.Source = new OOP.HoatDongUEHEntities().HoatDongCuocThiOnGoings;
        }
    }
}