//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConNguoiLop
    {
        public int Id { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> MaConNguoi { get; set; }
    
        public virtual ConNguoi ConNguoi { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
