//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoatDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoatDong()
        {
            this.HoatDongConNguois = new HashSet<HoatDongConNguoi>();
            this.HoatDongCoSoes = new HashSet<HoatDongCoSo>();
        }
    
        public int MaHoatDong { get; set; }
        public string TenHoatDong { get; set; }
        public Nullable<System.DateTime> NgayToChuc { get; set; }
        public Nullable<int> MaDonVi { get; set; }
        public Nullable<int> MaNhomHoatDong { get; set; }
        public Nullable<bool> HocKi { get; set; }
        public Nullable<int> SLSV { get; set; }
        public Nullable<float> DiemDanhGia { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public byte[] Picture { get; set; }
        public string Description { get; set; }
        public string Requirements { get; set; }
        public string Benefits { get; set; }
        public string Targets { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual NhomHoatDong NhomHoatDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoatDongConNguoi> HoatDongConNguois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoatDongCoSo> HoatDongCoSoes { get; set; }
    }
}
